### ISSUE TITLE
Week 3 Review Ticket - WIP Project Review

### ISSUE THREAD

**Issue by cactico** [MadCacti/PARK-tech#12]
Team.
- All 5 BOFs illustrate deliverables in areas of expertise
- Design Manager showing Bootstrap layouts, and at least 3 frontend screens screens with functionality toward Project Theme.
- Scrum Master overview of progress using GitHub README, Tickets (Completed and Backlog), and Wiki.  Show expected backlog when returning from Winter Break.
- Technical officer highlighting Asynchronous access(es) to a Database (expectation is a Search and/or a CRUD operations).
Deployment manager showing Web Site running from URL (https), and demonstrating the process to perform an update.
- GitHub admin highlighting commits and pull requests completed by each individual (just commits for us)

Individual
- AP MCQ Test and Corrections (2 pts)
- College Board Quiz and Journal for 3.11, 3.12, 3.13 due Tuesday the 14

Grading Plan - 6 minute live review, plus a 1 minute video by Technical Officer and Scrum Master on Asynchronous Data Access according to Create Task Guidelines. Kurtis and Raiden are responsible for the short video.

**Comment by cactico** [comment]
### Team Section:
**Scrum Master/Technical Officer**
- PBL Highlights: [link to week 3 timebox](https://github.com/MadCacti/PARK-tech#Week-3)
- [Video](https://youtu.be/QrnjChhsUpQ)

**Design Manager tangibles**
- NOTE: Due to deployment policy, some of these may not be up until tonight(12/16), but will include links to commits for feature 2/3(as they are combined in a sense).
- [Layout](https://github.com/MadCacti/PARK-tech/blob/main/templates/layouts/base.html)
- [Front End Feature Screen](https://parktech.cf/)
- [Front End Feature 2 - CHECK NAV.html](https://github.com/MadCacti/PARK-tech/commit/ac41484e9b2e75161d04031499c61ac4cfa5fb51) and [Link to direct .html](https://github.com/MadCacti/PARK-tech/blob/main/templates/layouts/nav.html)
- Front End Feature 3 included in nav.html, as a clickable popup. I will post link to runtime when it's done tonight, but it will show up on the home page.

**Scrum Master tangibles**
- [Scrumboard](https://github.com/MadCacti/PARK-tech/projects/1)
- Winter break backlog is in backlog/to-do, first column of scrum board

**Technical Officer tangibles**
- Database with Crud - We are currently running into some issues that I wanted to ask you about, since our group was generally confused and was not a finalized update before the deadline following our github/deployment guidelines.
- [View](https://github.com/MadCacti/PARK-tech/blob/main/mortencrud/app_crud.py)
- [Model](https://github.com/MadCacti/PARK-tech/blob/main/mortencrud/model.py)

**Deployment Manager tangibles**
- Update procedure is still the same, [link](https://github.com/MadCacti/PARK-tech/wiki/Policies#deployment)
- [Nginx config](https://github.com/MadCacti/PARK-tech/wiki/Policies#screenshot-of-https-runtime)
- [Service config](https://github.com/MadCacti/PARK-tech/wiki/Policies#screenshot-of-service-file-for-reference)

**Github Admin tangibles**
- Commit/PR procedure(we are not using PR's at the moment)[Link](https://github.com/MadCacti/PARK-tech/wiki/Policies#contributing-policies)
- Branching procedure, we are not using PR's/Branches, therefore we do not have one. As stated in the Contributing policies: 
**"Pull requests/branches as of now will not be used but may be potentially incorporated in the future depending on the project"**


### Individual Section: 
- [Paul and Armaan](https://docs.google.com/document/d/1oFeL4nMMEJ1XYFTJkGe01dahlJuVwP_HnVrcs5Kghuw/edit)
- [Kurtis and Raiden](https://docs.google.com/document/d/10IgexoJxVsm1w9mi2x22ORh4LrgRvdUqF__PXGfAcns/edit)

### Scores:
May seem a bit off, but based on amount of work put into getting things to work and getting tasks completed.

Raiden: 8/8 Added important PBL commits, updated and tidied up README, Wiki Policies, Deployment Policies, and Scrumboard. Helped Paul with deployment, set up backup with AWS in case things go awry with the main file.
Kurtis: 7.7/8. Completed all tasks, helped with database learning and video. Added PBL commits. Fixed the database and will be added on next runtime update. CRUD is still having a few issues, but they seem to be resolveable
Armaan: 7.7/8. Completed all the Frontend Features and look really nice. Added them and will be added on next runtime update.
Paul(edited before 6pm runtime deadline): 7.7/8. Certified and deployed website after resolving issues. Would still appreciate if commit descriptions made more logical sense instead of 'Paul Change'. All other tasks completed. One of the tasks done early(week before this technically) so bonus point.

Please note that most of our things occurred on the Thursday right before the runtime update deadline.
If you have any questions/concerns contact me on slack (for Mr. M).

**Comment by MadCacti** [comment]
If the scale is out of 7(though I've seen both so unsure) then grades will go:
Raiden: 6.85/7
Kurtis: 6.65/7
Armaan: 6.65/7
Paul: 6.5/7
