### ISSUE TITLE
Review Ticket - Week 1

### ISSUE THREAD

**Issue by cactico** [MadCacti/PARK-tech#13]
Leave review comments here.

**Comment by NathanShih04** [comment]
Name | Grade
Raiden | 5/5
Paul | 5/5
Armaan | 5/5
Kurtis | 5/5

Design: Brainwrite and wireframe is completed and thorough. Shows good planning.
Management: Had solid procedures and rules that were layed out for the team to follow.
Technicals: Were present and showed understanding of requirements.
Deployment plan: Well explained and showed a good process being planned out.
Scrum Board: Scrumboard was being utilized and had all the proper tasks assigned.
